'use client'

import { FirestoreService } from './firestoreService'
import { QRPayment, CreateQRPaymentInput, UpdateQRPaymentInput } from '../models/qrPayment.types'
import { ServiceResponse } from '../types'

const COLLECTION_NAME = 'qrPayments'

class QRPaymentService {
  private service: FirestoreService

  constructor() {
    this.service = new FirestoreService(COLLECTION_NAME)
  }

  async getQRPaymentById(id: string): Promise<ServiceResponse<QRPayment>> {
    return this.service.getById<QRPayment>(id)
  }

  async getQRPaymentByCode(qrCode: string): Promise<ServiceResponse<QRPayment | null>> {
    const response = await this.service.getAll<QRPayment>([
      { field: 'qrCode', operator: '==', value: qrCode },
    ])

    if (!response.success || !response.data || response.data.length === 0) {
      return { success: true, data: null }
    }

    return { success: true, data: response.data[0] }
  }

  async getQRPaymentsByStore(storeId: string): Promise<ServiceResponse<QRPayment[]>> {
    return this.service.getAll<QRPayment>([
      { field: 'storeId', operator: '==', value: storeId },
    ])
  }

  async getActiveQRPayments(storeId: string): Promise<ServiceResponse<QRPayment[]>> {
    return this.service.getAll<QRPayment>([
      { field: 'storeId', operator: '==', value: storeId },
      { field: 'status', operator: '==', value: 'active' },
    ])
  }

  async createQRPayment(input: CreateQRPaymentInput): Promise<ServiceResponse<QRPayment & { id: string }>> {
    // Generate unique QR code (in real implementation, this would be generated by a Cloud Function)
    const qrCode = `QR_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
    const qrImage = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(qrCode)}`

    const qrPaymentData: QRPayment = {
      id: '',
      storeId: input.storeId,
      cashierId: input.cashierId,
      qrCode,
      qrImage,
      amount: input.amount,
      currency: input.currency,
      status: 'active',
      validUntil: input.validUntil,
      metadata: input.metadata || {},
      createdAt: new Date(),
      updatedAt: new Date(),
    }

    return this.service.create<QRPayment>(qrPaymentData)
  }

  async updateQRPayment(id: string, input: UpdateQRPaymentInput): Promise<ServiceResponse<void>> {
    return this.service.update<QRPayment>(id, input)
  }

  async markQRPaymentAsUsed(id: string, transactionId: string): Promise<ServiceResponse<void>> {
    return this.service.update<QRPayment>(id, {
      status: 'used',
      transactionId,
      usedAt: new Date(),
    })
  }

  async expireQRPayment(id: string): Promise<ServiceResponse<void>> {
    return this.service.update<QRPayment>(id, {
      status: 'expired',
    })
  }

  async cancelQRPayment(id: string): Promise<ServiceResponse<void>> {
    return this.service.update<QRPayment>(id, {
      status: 'cancelled',
    })
  }

  async deleteQRPayment(id: string): Promise<ServiceResponse<void>> {
    return this.service.hardDelete(id)
  }
}

export const qrPaymentService = new QRPaymentService()
